# Mix of host and pod mounts for ticket management
node:
  extraVolumes:
    - name: krb5-cache
      hostPath:
        path: /var/lib/kubelet/kerberos
        type: DirectoryOrCreate
    - name: krb5-conf
      hostPath:
        path: /etc/krb5.conf
        type: File
    - name: sssd-pipes
      hostPath:
        path: /var/lib/sss/pipes
        type: Directory

  extraVolumeMounts:
    - name: krb5-cache
      mountPath: /var/lib/kubelet/kerberos
    - name: krb5-conf
      mountPath: /etc/krb5.conf
      readOnly: true
    - name: sssd-pipes
      mountPath: /var/lib/sss/pipes