# mount the SSSD KCM socket so the CSI node plugin can access host tickets:
node:
  extraVolumes:
    - name: krb5-conf
      hostPath:
        path: /etc/krb5.conf
        type: File
    - name: sssd-pipes
      hostPath:
        path: /var/lib/sss/pipes
        type: Directory

  extraVolumeMounts:
    - name: krb5-conf
      mountPath: /etc/krb5.conf
      readOnly: true
    - name: sssd-pipes
      mountPath: /var/lib/sss/pipes