## Security context give the opportunity to run container as nonroot by setting a securityContext
## by example :
#securityContext: { runAsUser: 1001 }
#securityContext: { seccompProfile: {type: RuntimeDefault} }
## StorageClass resources for creating multiple storage classes:
# storageClasses:
#   - name: smb-csi
#     annotations:
#       storageclass.kubernetes.io/is-default-class: "true"
#     parameters:
#       source: "//smb-server.default.svc.cluster.local/share"
#       # if csi.storage.k8s.io/provisioner-secret is provided, will create a sub directory
#       # with PV name under source
#       csi.storage.k8s.io/provisioner-secret-name: smbcreds
#       csi.storage.k8s.io/provisioner-secret-namespace: default
#       csi.storage.k8s.io/node-stage-secret-name: smbcreds
#       csi.storage.k8s.io/node-stage-secret-namespace: default
#     reclaimPolicy: Delete
#     volumeBindingMode: Immediate
#     allowVolumeExpansion: true
#     mountOptions:
#       - dir_mode=0777
#       - file_mode=0777
#       - noperm
#       - mfsymlinks
#       - cache=strict
#       - noserverino  # required to prevent data corruption
#   - name: smb-csi-retain
#     parameters:
#       source: "//smb-server.default.svc.cluster.local/share"
#       # if csi.storage.k8s.io/provisioner-secret is provided, will create a sub directory
#       # with PV name under source
#       csi.storage.k8s.io/provisioner-secret-name: smbcreds
#       csi.storage.k8s.io/provisioner-secret-namespace: default
#       csi.storage.k8s.io/node-stage-secret-name: smbcreds
#       csi.storage.k8s.io/node-stage-secret-namespace: default
#     reclaimPolicy: Delete
#     volumeBindingMode: Immediate
#     allowVolumeExpansion: true
#     mountOptions:
#       - dir_mode=0777
#       - file_mode=0777
#       - noperm
#       - mfsymlinks
#       - cache=strict
#       - noserverino  # required to prevent data corruption
